# Generated by Django 3.0.5 on 2020-06-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('Gross_Production_Value_constant_2004_2006_1000_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Net_Production_Value_constant_2004_2006_1000_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_current_million_SLC', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_constant_2004_2006_million_SLC', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_current_million_US_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_constant_2004_2006_million_US_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='pred_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('Gross_Production_Value_constant_2004_2006_1000_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Net_Production_Value_constant_2004_2006_1000_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_current_million_SLC', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_constant_2004_2006_million_SLC', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_current_million_US_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('Gross_Production_Value_constant_2004_2006_million_US_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('org_mean_Gross_Production_Value_constant_2004_2006_million_US_dollar', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='pred_three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('imports', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('exports', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('production', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('production_mean', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('imports_mean', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('exports_mean', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='prod_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('crop', models.CharField(max_length=25)),
                ('org_val', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('pred_val', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('Production', models.IntegerField()),
                ('Imports', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Export', models.IntegerField()),
                ('Seed', models.IntegerField()),
                ('Domestic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=25)),
                ('area_harvested', models.IntegerField()),
                ('yieldd', models.IntegerField()),
                ('production', models.IntegerField()),
            ],
        ),
    ]
